import { motion } from 'framer-motion';
import { ArrowLeft, Shield, Volume2, Anchor, Layers } from 'lucide-react';
import { Link } from 'react-router-dom';
import vibrationPadsHero from '../assets/vibration_pads_hero.webp';

interface ProductType {
    name: string;
    description: string;
    icon: React.ReactNode;
}

const VibrationPads = () => {
    const fadeInUp = {
        initial: { opacity: 0, y: 20 },
        animate: { opacity: 1, y: 0 },
        transition: { duration: 1.0, ease: [0.25, 0.1, 0.25, 1] }
    };

    const staggerContainer = {
        animate: {
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    const applications = [
        'Machinery vibration damping',
        'Noise reduction in industrial operations',
        'Equipment stabilization for conveyors, compressors, generators, etc.',
        'Isolation under mounted machinery to reduce floor transmitted vibration'
    ];

    const productTypes: ProductType[] = [
        {
            name: 'Rubber Vibration Pads',
            description: 'Used for general vibration and noise reduction in industrial machinery.',
            icon: <Layers className="h-8 w-8" />
        },
        {
            name: 'Cork & Rubber Composite Pads',
            description: 'Suitable for heavy loads and impact absorption applications.',
            icon: <Shield className="h-8 w-8" />
        },
        {
            name: 'Neoprene Anti-Vibration Pads',
            description: 'Resistant to oil, chemicals, and weathering for demanding environments.',
            icon: <Shield className="h-8 w-8" />
        },
        {
            name: 'Spring Isolators',
            description: 'Designed for high-load and low-frequency vibration control.',
            icon: <Anchor className="h-8 w-8" />
        },
        {
            name: 'Machine Leveling Pads',
            description: 'Combine vibration isolation with equipment leveling for precise positioning.',
            icon: <Anchor className="h-8 w-8" />
        },
        {
            name: 'Shock Absorbing Pads & Mounts',
            description: 'Used for dynamic load and impact applications requiring energy absorption.',
            icon: <Volume2 className="h-8 w-8" />
        }
    ];

    return (
        <div className="min-h-screen bg-neutral-50 pt-20">
            {/* Header */}
            <div className="bg-white shadow-sm border-b border-neutral-200">
                <div className="container-max">
                    <div className="flex items-center justify-between py-6">
                        <Link
                            to="/#products"
                            className="inline-flex items-center text-neutral-600 hover:text-neutral-900 transition-colors duration-200"
                        >
                            <ArrowLeft className="h-5 w-5 mr-2" />
                            Back to Products
                        </Link>
                    </div>
                </div>
            </div>

            {/* Hero Section */}
            <section className="bg-white py-12">
                <div className="container-max">
                    <motion.div
                        variants={fadeInUp}
                        initial="initial"
                        animate="animate"
                        className="text-center mb-12"
                    >
                        <h1 className="text-4xl md:text-5xl font-bold text-neutral-900 mb-6">
                            Vibration Pads & Anti-Vibration Products
                        </h1>
                        <p className="text-xl text-neutral-600 max-w-4xl mx-auto leading-relaxed mb-6">
                            Our vibration pads and anti-vibration products are designed to absorb shock, reduce noise, and isolate vibrations generated by industrial machinery and equipment. These products help protect machines, floors, and surrounding structures while improving equipment performance and service life.
                        </p>
                        <p className="text-lg text-neutral-600 max-w-4xl mx-auto leading-relaxed">
                            They are widely used under compressors, generators, motors, pumps, HVAC units, conveyor systems, and heavy industrial machinery.
                        </p>
                    </motion.div>

                    {/* Hero Image */}
                    <motion.div
                        variants={fadeInUp}
                        initial="initial"
                        whileInView="animate"
                        viewport={{ once: true }}
                        className="flex justify-center mb-16"
                    >
                        <div className="bg-white rounded-lg shadow-lg overflow-hidden max-w-2xl">
                            <div className="h-80 flex items-center justify-center overflow-hidden">
                                <img
                                    src={vibrationPadsHero}
                                    alt="Vibration Pads & Anti-Vibration Products"
                                    className="w-full h-full object-cover"
                                />
                            </div>
                        </div>
                    </motion.div>
                </div>
            </section>

            {/* Applications Section */}
            <section className="py-12 bg-neutral-100">
                <div className="container-max">
                    <motion.div
                        variants={fadeInUp}
                        initial="initial"
                        whileInView="animate"
                        viewport={{ once: true }}
                        className="text-center mb-10"
                    >
                        <h2 className="text-3xl font-bold text-neutral-900 mb-4">
                            Applications
                        </h2>
                        <p className="text-lg text-neutral-600 max-w-3xl mx-auto">
                            Our vibration pads are ideal for use under heavy equipment, conveyor systems, motors, compressors, pumps, generators, and HVAC units.
                        </p>
                    </motion.div>

                    <motion.div
                        className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto"
                        variants={staggerContainer}
                        initial="initial"
                        whileInView="animate"
                        viewport={{ once: true }}
                    >
                        {applications.map((app, index) => (
                            <motion.div
                                key={index}
                                variants={fadeInUp}
                                className="flex items-start bg-white rounded-lg p-6 shadow-md"
                            >
                                <div className="flex-shrink-0 w-10 h-10 bg-primary-100 rounded-full flex items-center justify-center mr-4">
                                    <span className="text-primary-600 font-bold">{index + 1}</span>
                                </div>
                                <p className="text-neutral-700 text-lg">{app}</p>
                            </motion.div>
                        ))}
                    </motion.div>
                </div>
            </section>

            {/* Product Types Section */}
            <section className="py-16">
                <div className="container-max">
                    <motion.div
                        variants={fadeInUp}
                        initial="initial"
                        whileInView="animate"
                        viewport={{ once: true }}
                        className="text-center mb-12"
                    >
                        <h2 className="text-3xl font-bold text-neutral-900 mb-4">
                            Types of Products We Supply
                        </h2>
                    </motion.div>

                    <motion.div
                        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8"
                        variants={staggerContainer}
                        initial="initial"
                        whileInView="animate"
                        viewport={{ once: true }}
                    >
                        {productTypes.map((product, index) => (
                            <motion.div
                                key={index}
                                variants={fadeInUp}
                                className="bg-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 border border-neutral-100"
                            >
                                <div className="w-16 h-16 bg-gradient-to-br from-primary-500 to-primary-600 rounded-xl flex items-center justify-center text-white mb-6">
                                    {product.icon}
                                </div>
                                <h3 className="text-xl font-bold text-neutral-900 mb-3">
                                    {product.name}
                                </h3>
                                <p className="text-neutral-600 leading-relaxed">
                                    {product.description}
                                </p>
                            </motion.div>
                        ))}
                    </motion.div>

                    {/* Note Section */}
                    <motion.div
                        variants={fadeInUp}
                        initial="initial"
                        whileInView="animate"
                        viewport={{ once: true }}
                        className="mt-12 bg-primary-50 rounded-xl p-8 text-center"
                    >
                        <p className="text-lg text-neutral-700">
                            <strong>Custom Solutions:</strong> All vibration pads and anti-vibration solutions can be supplied in standard sizes or customized based on load capacity, thickness, and application requirements.
                        </p>
                    </motion.div>
                </div>
            </section>
        </div>
    );
};

export default VibrationPads;
